---
- name: "Step3 仮想マシンのパワーオン"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "仮想マシンをONする"
    vmware_guest:
      name: "{{ vmname }}"
      hostname: "{{lookup('env', 'VMWARE_HOST')}}"
      username: "{{lookup('env', 'VMWARE_USER')}}"
      password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
      datacenter: "{{ datacenter_name }}"
      esxi_hostname: "{{ esxi_hostname }}"
      state: poweredon
      validate_certs: false
      wait_for_ip_address: yes
    delegate_to: localhost
